position = "top"
height = 32
width = 0
monitor = ""
web_content_path = "/home/tieppo/.config/hyprbar/web"
layer = "top"

[margins]
top = 0
bottom = 0
left = 0
right = 0

[hot_reload]
enabled = true
debounce_ms = 200
recursive = true

[rendering]
vsync = true
target_fps = 60
antialiasing = true
backend = "auto"
transparency = true
background_color = [
    0.10000000149011612,
    0.10000000149011612,
    0.10000000149011612,
    0.8999999761581421,
]

[hyprland]
enabled = true
socket_path = ""
events = [
    "workspace",
    "activewindow",
    "activewindowv2",
    "fullscreen",
    "monitoradded",
    "monitorremoved",
    "urgent",
]
